### ISSUE TITLE
Binding to host error (adidnsdump)

### ISSUE THREAD

**Issue by user987429837429834** [lefayjey/linWinPwn#11] opened 2023-02-09 15:54 UTC
Hello Guys,

when i try to start and connect with linWinPwn i get the following error from adidnsdump.

my command: ./linWinPwn -t <AD-Domain> -u <AD-Username> -p <AD-Passwort> --auto-config 

![Screenshot_2023-02-09_09-51-56](https://user-images.githubusercontent.com/124906543/217865488-e0494cc7-0b1f-420d-97b7-671468b878e5.png)

**Comment by lefayjey** [comment] 2023-02-09 16:16
Hello, 
From the error message, it seems like you're using ldaps instead of ldap (i.e. port 636 instead of 389). Did you specify the parameter `--ldaps` with linWinPwn?
Also, are you sure to be using the latest version of adidnsdump?

**Comment by user987429837429834** [comment] 2023-02-09 16:25
Hello lefayjey,

Thanks for the quick respond.

Yes, i also tried it with --ldaps parameter. Same problem.

adidnsdump is also on the latest version.

Br!

**Comment by lefayjey** [comment] 2023-02-09 16:43
If you run the command `adidnsdump` followed by the same IP, do you have the same error? 

The issue can be related to adidnsdump, or the target IP could be blocking the connection or just doesn't have the LDAP ports open

**Comment by user987429837429834** [comment] 2023-02-09 16:48
Yes.

im connected to LAN.

I tried the bloodhound python script and it worked, so i think its something with adidnsdump.

Do you know how bloodhound bind to hosts ?

Br!

**Comment by lefayjey** [comment] 2023-02-09 17:24
If the issue is with adidnsdump, then it's not related to linWinPwn, and I can't really help you with that.
If you wish to skip the dns enumeration and use the checks of linWinPwn, you'll have to comment the line "dns_enum" under the "main()" function (line 2330 in the latest version), but some checks may fail because of that.

**Comment by lefayjey** [comment] 2023-02-12 20:14
I'm going to close this issue since it seems to be related to  another tool. I'll keep the comments on in case you need more assistance on that. 
Thanks

**Closed by lefayjey** 2023-02-12 20:14 UTC
